### ISSUE TITLE
gtk is not ready

### ISSUE THREAD

**Issue by lidaobing** [linuxdeepin/go-gir#3]
```
$ out/gir-generator -o out/src/gir/gtk-3.0 lib.in/gtk-3.0/gtk.go.in
panic: It hasn't implemnt converting the type of gslist from go to cgo.

goroutine 1 [running]:
main.go_to_cgo(0xc4202c2300, 0xc4202bb380, 0xd, 0xc4202bb390, 0xd, 0x0, 0xd, 0x5a)
	/Users/lidaobing/workspace/foss/go-gir-generator/src/gir-generator/typeconv.go:188 +0x1600
main.(*binding_generator).process_function_info(0xc420112b40, 0xc4202c2278)
	/Users/lidaobing/workspace/foss/go-gir-generator/src/gir-generator/binding_generator.go:894 +0xef3
main.(*binding_generator).process_struct_info(0xc420112b40, 0xc4202c2018)
	/Users/lidaobing/workspace/foss/go-gir-generator/src/gir-generator/binding_generator.go:570 +0x32e
main.(*binding_generator).process_base_info(0xc420112b40, 0xc4202c2018)
	/Users/lidaobing/workspace/foss/go-gir-generator/src/gir-generator/binding_generator.go:1092 +0x412
main.(*binding_generator).generate(0xc420112b40, 0xc42011c800, 0x40a1)
	/Users/lidaobing/workspace/foss/go-gir-generator/src/gir-generator/binding_generator.go:66 +0xb3
main.main()
	/Users/lidaobing/workspace/foss/go-gir-generator/src/gir-generator/main.go:227 +0x3cd
```

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
